name: museum_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # Default Icon font
  cupertino_icons: ^1.0.8

  # --- ADDED FOR MUSEUM APP ---
  # 1. State Management (Connects logic to UI)
  provider: ^6.1.2

  # 2. Local Storage (Saves settings like Language/Dark Mode)
  shared_preferences: ^2.2.3

  # 3. Localization (Handles Arabic/English logic)
  intl: ^0.19.0

  # 4. Audio (Plays the robot voice narration)
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0 # Note: Downgraded slightly to ensure compatibility with sdk 3.10.1

flutter:
  uses-material-design: true

  # To add assets (images) later, uncomment lines below:
  assets:
    - assets/images/
    - assets/audio/
